/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-03-06 05:45:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BookSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Book Search and Availability</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <style>\r\n");
      out.write("            table {\r\n");
      out.write("                border: 1px solid #666;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            th {\r\n");
      out.write("                background: #f8f8f8;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                padding: 2px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            jQuery(window).ready(function() {\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                $(\"#searchButton\").click(function(event) {\r\n");
      out.write("                    \r\n");
      out.write("                    var filled = $('#searchBook').val();\r\n");
      out.write("                    console.log(\"hello\");\r\n");
      out.write("                    jQuery.ajax({\r\n");
      out.write("                        url: \"PopulateBook\",\r\n");
      out.write("                        type: \"get\",\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        data: {\r\n");
      out.write("                            term: filled\r\n");
      out.write("                        },\r\n");
      out.write("                        success: function(data) {\r\n");
      out.write("                            // since we are using jQuery, you don't need to parse response\r\n");
      out.write("                            console.log(\"data\", data);\r\n");
      out.write("\r\n");
      out.write("                            drawTable(data);\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                function drawTable(data) {\r\n");
      out.write("                \t  $(\"#bookTable\").find(\"tr:not(:first)\").remove();\r\n");
      out.write("                    for (var i = 0; i < data.length; i++) {\r\n");
      out.write("                        drawRow(data[i]);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function drawRow(rowData) {\r\n");
      out.write("                    var row = $(\"<tr />\");\r\n");
      out.write("                    $(\"#bookTable\").append(row); //this will append tr element to table... keep its reference for a while since we will add cels into it\r\n");
      out.write("                    row.append($(\"<td>\" + rowData.isbn + \"</td>\"));\r\n");
      out.write("                    row.append($(\"<td>\" + rowData.title + \"</td>\"));\r\n");
      out.write("                    row.append($(\"<td>\" + rowData.name + \"</td>\"));\r\n");
      out.write("                    row.append($(\"<td>\" + rowData.avail + \"</td>\"));\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2>\r\n");
      out.write("                <font color=\"red\">Book Search and Availability</font>\r\n");
      out.write("            </h2>\r\n");
      out.write("\t\t\t</br></br>\r\n");
      out.write("            <div class=\"searchArea\">\r\n");
      out.write("                <label for=\"searchBook\"><h3>Type Search String:</h3></label></br></br>\r\n");
      out.write("                <input type=\"text\" width = \"48px\" height = \"10px\" id=\"searchBook\" placeholder=\"Search Book..\" name=\"search\"></br></br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-default\" id=\"searchButton\">Submit</button></br></br>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <table id=\"bookTable\" border=\"1\" style=\"border-collapse: collapse;\" cellpadding=\"8\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Isbn</th>\r\n");
      out.write("                <th>Title</th>\r\n");
      out.write("                <th>Name</th>\r\n");
      out.write("                <th>Availability</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
