/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-02-24 07:24:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BorrowerEntry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Borrower Entry </title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            jQuery(window).ready(function() {\r\n");
      out.write("\r\n");
      out.write("                $(\"#newBorrower\").click(function(event) {\r\n");
      out.write("                    \r\n");
      out.write("                    var ssn = $('#ssn').val();\r\n");
      out.write("                    var name = $('#name').val();\r\n");
      out.write("                    var address = $('#address').val();\r\n");
      out.write("                    var phone = $('#phone').val();\r\n");
      out.write("                    jQuery.ajax({\r\n");
      out.write("                        url: \"NewBorrowerServlet\",\r\n");
      out.write("                        type: \"get\",\r\n");
      out.write("                        dataType: \"json\",\r\n");
      out.write("                        data: {\r\n");
      out.write("                            ssn: ssn,\r\n");
      out.write("                            name: name,\r\n");
      out.write("                            address: address,\r\n");
      out.write("                            phone: phone\r\n");
      out.write("                        },\r\n");
      out.write("                        success: function(data) {\r\n");
      out.write("                            // since we are using jQuery, you don't need to parse response\r\n");
      out.write("                            if(data[0].flag_maxLimit == 0 ){\r\n");
      out.write("                                alert(\"Error: Each BORROWER is permitted a maximum of 1 library card\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if(data[0].flag_ssn == 0 ){\r\n");
      out.write("                                alert(\"Error: SSN cannot be NULL\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if(data[0].flag_name == 0 ){\r\n");
      out.write("                                alert(\"Error: Name cannot be NULL\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if(data[0].flag_address == 0 ){\r\n");
      out.write("                                alert(\"Error: Address cannot be NULL\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if(data[0].flag_maxLimit == 1 && data[0].flag_ssn == 1 && data[0].flag_name == 1 && data[0].flag_address == 1 ){\r\n");
      out.write("                                alert(\"Borrower Record successfully created\");\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2>\r\n");
      out.write("                <font color=\"red\">Enter a new Borrower Record</font>\r\n");
      out.write("            </h2>\r\n");
      out.write("\t\t\t</br></br>\r\n");
      out.write("            <div class=\"newBorrower\">\r\n");
      out.write("                <label for=\"newBorrower\"><h3>Enter details of the Borrower</h3></label></br></br>\r\n");
      out.write("                SSN: <input type=\"text\" id=\"ssn\" placeholder=\"SSn...\" name=\"ssn\"></br></br>\r\n");
      out.write("                Name: <input type=\"text\" id=\"name\" placeholder=\"Name..\" name=\"name\"></br></br>\r\n");
      out.write("                Address: <input type=\"text\" id=\"address\" placeholder=\"Address..\" name=\"address\"></br></br>\r\n");
      out.write("                Phone No: <input type=\"text\" id=\"phone\" placeholder=\"Phone No..\" name=\"phone\"></br></br>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</br>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-default\" id=\"newBorrower\">Submit</button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
