/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-03-03 02:00:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Book Search and Availability</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\ta:link {\r\n");
      out.write("    color: green;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("    color: blue\t;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("    color: red;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("a:active {\r\n");
      out.write("    color: yellow;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1><font color = \"red\">Welcome to the Online Library Management System</font></h1>\r\n");
      out.write("\t\t\t</br></br>\r\n");
      out.write("\t\t\t<ul class=\"nav nav-pills\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a data-toggle=\"pill\" href=\"#BookSearch\">Book Search and Availability</a></li>\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"pill\" href=\"#BookLoans\">Book Loans</a></li>\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"pill\" href=\"#BorrowerManagement\">Borrower Management</a></li>\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"pill\" href=\"#Fines\">Fines</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div id=\"BookSearch\" class=\"tab-pane fade in active\">\r\n");
      out.write("\t\t\t\t<h3><font color = \"green\"><strong>Book Search and Availability</strong></font></h3></br>\r\n");
      out.write("\t\t\t\t<h4>Searches for a book, given any combination of ISBN, title, and/\r\n");
      out.write("\t\t\t\tor Author(s)</h4></br>\r\n");
      out.write("\t\t\t\t<h4><a href=\"BookSearch.jsp\" target=\"_blank\">Visit Book Search Page</a> </h4>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"BookLoans\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t\t<h3><font color = \"green\"><strong>Book Loans</strong></font></h3></br>\r\n");
      out.write("\t\t\t\t<h4>Facilitates Checking in and Checking out of books.</h4></br>\r\n");
      out.write("\t\t\t\t<h4><a href=\"CheckOutIn.jsp\" target=\"_blank\">Visit Check Out Page</a> </h4></br>\r\n");
      out.write("\t\t\t\t<h4><a href=\"CheckIn.jsp\" target=\"_blank\">Visit Check In Page</a> </h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"BorrowerManagement\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t\t<h3><font color = \"green\"><strong>Borrower Management</strong></font></h3></br>\r\n");
      out.write("\t\t\t\t<h4>Create new borrowers in the system</h4></br>\r\n");
      out.write("\t\t\t\t<h4><a href=\"BorrowerEntry.jsp\" target=\"_blank\">Visit Borrower Entry Page</a> </h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"Fines\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t\t<h3><font color = \"green\"><strong>Fines</strong></font></h3></br>\r\n");
      out.write("\t\t\t\t<h4>Handles fine management</h4></br>\r\n");
      out.write("\t\t\t\t<h4><a href=\"Fines.jsp\" target=\"_blank\">Visit Fine Update Page</a> </h4></br>\r\n");
      out.write("\t\t\t\t<h4><a href=\"FinePay.jsp\" target=\"_blank\">Visit Fine Pay / Display Page</a> </h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
