
--CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE BOOK(
Isbn CHAR(10),
Title VARCHAR(100),
CONSTRAINT pk_Book PRIMARY KEY(Isbn)
);
	

CREATE TABLE AUTHORS(
Author_id INT(10) AUTO_INCREMENT,
Name VARCHAR(50),
CONSTRAINT pk_Authors PRIMARY KEY(Author_id)
);
	
CREATE TABLE BOOK_AUTHORS(
Author_id INT(10),
Isbn CHAR(10),
CONSTRAINT pk_book_authors PRIMARY KEY(Author_id, Isbn),
CONSTRAINT fk_book_authors_authors FOREIGN KEY(Author_id) references AUTHORS(Author_id)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_book_authors_book FOREIGN KEY(Isbn) REFERENCES BOOK(Isbn)
ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BORROWER(
Card_id INT(6) AUTO_INCREMENT,
Ssn VARCHAR(11) NOT NULL,
Bname VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Phone VARCHAR(14),  
CONSTRAINT pk_Borrowers PRIMARY KEY(Card_id),
CONSTRAINT un_borrower UNIQUE (ssn)
);
	
CREATE TABLE BOOK_LOANS(
Loan_id INT(10) AUTO_INCREMENT,
Isbn CHAR(10),
Card_id INT(6),
Date_out DATE,
Due_date DATE,
Date_in DATE default NULL,
CONSTRAINT pk_book_loans PRIMARY KEY(loan_id),
CONSTRAINT fk_book_loans_book FOREIGN KEY(Isbn) references BOOK(Isbn)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_book_loans_borrowers FOREIGN KEY(Card_id) REFERENCES BORROWER(Card_id)
ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE FINES(
Loan_id INT(10),
Fine_amt DECIMAL(13,2),
Paid CHAR(1),
CONSTRAINT pk_Fines PRIMARY KEY(Loan_id),
CONSTRAINT fk_fines_book_loans FOREIGN KEY (Loan_id) references BOOK_LOANS(loan_id)
ON DELETE CASCADE ON UPDATE CASCADE
);
	
--ALTER TABLE BORROWER ADD CONSTRAINT un_borrower UNIQUE (ssn);
--ALTER TABLE BORROWER MODIFY ssn VARCHAR(11) NOT NULL;
--ALTER TABLE BORROWER MODIFY bname VARCHAR(50) NOT NULL;
--ALTER TABLE BORROWER MODIFY address VARCHAR(50) NOT NULL--;
--ALTER TABLE BORROWER MODIFY Card_id INT(6) AUTO_INCREMENT;
--ALTER TABLE BORROWER MODIFY phone VARCHAR(14);
--ALTER TABLE BOOK MODIFY isbn CHAR(10);
--ALTER TABLE BOOK_AUTHORS MODIFY isbn CHAR(10);
--ALTER TABLE BOOK_LOANS MODIFY Loan_id INT(10) AUTO_INCREMENT;
--ALTER TABLE BOOK_LOANS MODIFY date_in DATE default NULL;
--ALTER TABLE book_loans MODIFY Card_id INT(6);
--ALTER TABLE BOOK_LOANS MODIFY isbn CHAR(10);
--ALTER TABLE FINES MODIFY paid INT(1); -- Implement this
--TER TABLE AUTHORS MODIFY Author_id INT(10) AUTO_INCREMENT
